#!/bin/bash
# Points Debug builds at your "Apple Development" certificate.
#
# Ad-hoc signatures change with every build, and macOS ties the Microphone
# permission to the signature — so without this you re-grant it after every
# rebuild. Config/Local.xcconfig is gitignored.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="$ROOT/Config/Local.xcconfig"

IDENTITY=$(security find-identity -v -p codesigning \
  | sed -n 's/.*"\(Apple Development: .*\)"/\1/p' | head -1)

if [ -z "$IDENTITY" ]; then
  echo "No 'Apple Development' identity in the keychain." >&2
  echo "Open Xcode → Settings → Accounts and add your Apple ID, then run this again." >&2
  exit 1
fi

TEAM=$(security find-certificate -c "Apple Development" -p \
  | openssl x509 -noout -subject 2>/dev/null \
  | tr ',/' '\n\n' | sed -n 's/^ *OU *= *//p' | head -1)

{
  echo "// Generated by scripts/setup_local_signing.sh — not tracked by git."
  echo "CODE_SIGN_IDENTITY = $IDENTITY"
  [ -n "$TEAM" ] && echo "DEVELOPMENT_TEAM = $TEAM"
} > "$TARGET"

echo "Wrote $TARGET"
sed 's/^/  /' "$TARGET"
